<?php namespace Codalia\Profile\Updates;

use Seeder;
use Illuminate\Support\Facades\DB;


class SeedListTables extends Seeder
{
    public $appealCourts = ['Agen', 'Aix en Provence', 'Amiens', 'Angers', 'Basse Terre',
			    'Bastia', 'Besançon', 'Bordeaux', 'Bourges', 'Caen', 'Cayenne',
			    'Chambéry', 'Colmar', 'Dijon', 'Douai', 'Fort de France', 'Grenoble',
			    'Limoges', 'Lyon', 'Metz', 'Montpellier', 'Nancy', 'Nîmes', 'Nouméa',
			    'Orléans', 'Papeete', 'Paris', 'Pau', 'Poitiers', 'Reims', 'Rennes',
			    'Riom', 'Rouen', 'Saint Denis', 'Saint Pierre', 'Toulouse', 'Versailles'
    ]; 


    public $countries = [['alpha_2' => 'AF', 'alpha_3' => 'AFG', 'numerical' => 4, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'AX', 'alpha_3' => 'ALA', 'numerical' => 248, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'AL', 'alpha_3' => 'ALB', 'numerical' => 8, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'DZ', 'alpha_3' => 'DZA', 'numerical' => 12, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'AS', 'alpha_3' => 'ASM', 'numerical' => 16, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'AD', 'alpha_3' => 'AND', 'numerical' => 20, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'AO', 'alpha_3' => 'AGO', 'numerical' => 24, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'AI', 'alpha_3' => 'AIA', 'numerical' => 660, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'AQ', 'alpha_3' => 'ATA', 'numerical' => 10, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AN', 'fr' => ''],
			 ['alpha_2' => 'AG', 'alpha_3' => 'ATG', 'numerical' => 28, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'AR', 'alpha_3' => 'ARG', 'numerical' => 32, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'AM', 'alpha_3' => 'ARM', 'numerical' => 51, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'AW', 'alpha_3' => 'ABW', 'numerical' => 533, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'AU', 'alpha_3' => 'AUS', 'numerical' => 36, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'AT', 'alpha_3' => 'AUT', 'numerical' => 40, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'AZ', 'alpha_3' => 'AZE', 'numerical' => 31, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'BS', 'alpha_3' => 'BHS', 'numerical' => 44, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'BH', 'alpha_3' => 'BHR', 'numerical' => 48, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'BD', 'alpha_3' => 'BGD', 'numerical' => 50, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'BB', 'alpha_3' => 'BRB', 'numerical' => 52, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'BY', 'alpha_3' => 'BLR', 'numerical' => 112, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'BE', 'alpha_3' => 'BEL', 'numerical' => 56, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'BZ', 'alpha_3' => 'BLZ', 'numerical' => 84, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'BJ', 'alpha_3' => 'BEN', 'numerical' => 204, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'BM', 'alpha_3' => 'BMU', 'numerical' => 60, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'BT', 'alpha_3' => 'BTN', 'numerical' => 64, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'BO', 'alpha_3' => 'BOL', 'numerical' => 68, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'BA', 'alpha_3' => 'BIH', 'numerical' => 70, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'BW', 'alpha_3' => 'BWA', 'numerical' => 72, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'BR', 'alpha_3' => 'BRA', 'numerical' => 76, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'VG', 'alpha_3' => 'VGB', 'numerical' => 92, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'IO', 'alpha_3' => 'IOT', 'numerical' => 86, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'BN', 'alpha_3' => 'BRN', 'numerical' => 96, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'BG', 'alpha_3' => 'BGR', 'numerical' => 100, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'BF', 'alpha_3' => 'BFA', 'numerical' => 854, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'BI', 'alpha_3' => 'BDI', 'numerical' => 108, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'KH', 'alpha_3' => 'KHM', 'numerical' => 116, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'CM', 'alpha_3' => 'CMR', 'numerical' => 120, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'CA', 'alpha_3' => 'CAN', 'numerical' => 124, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'CV', 'alpha_3' => 'CPV', 'numerical' => 132, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'KY', 'alpha_3' => 'CYM', 'numerical' => 136, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'CF', 'alpha_3' => 'CAF', 'numerical' => 140, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'TD', 'alpha_3' => 'TCD', 'numerical' => 148, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'CL', 'alpha_3' => 'CHL', 'numerical' => 152, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'CN', 'alpha_3' => 'CHN', 'numerical' => 156, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'HK', 'alpha_3' => 'HKG', 'numerical' => 344, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'MO', 'alpha_3' => 'MAC', 'numerical' => 446, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'CX', 'alpha_3' => 'CXR', 'numerical' => 162, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'CC', 'alpha_3' => 'CCK', 'numerical' => 166, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'CO', 'alpha_3' => 'COL', 'numerical' => 170, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'KM', 'alpha_3' => 'COM', 'numerical' => 174, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'CG', 'alpha_3' => 'COG', 'numerical' => 178, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'CD', 'alpha_3' => 'COD', 'numerical' => 180, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'CK', 'alpha_3' => 'COK', 'numerical' => 184, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'CR', 'alpha_3' => 'CRI', 'numerical' => 188, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'CI', 'alpha_3' => 'CIV', 'numerical' => 384, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'HR', 'alpha_3' => 'HRV', 'numerical' => 191, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'CU', 'alpha_3' => 'CUB', 'numerical' => 192, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'CY', 'alpha_3' => 'CYP', 'numerical' => 196, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'CZ', 'alpha_3' => 'CZE', 'numerical' => 203, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'DK', 'alpha_3' => 'DNK', 'numerical' => 208, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'DJ', 'alpha_3' => 'DJI', 'numerical' => 262, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'DM', 'alpha_3' => 'DMA', 'numerical' => 212, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'DO', 'alpha_3' => 'DOM', 'numerical' => 214, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'EC', 'alpha_3' => 'ECU', 'numerical' => 218, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'EG', 'alpha_3' => 'EGY', 'numerical' => 818, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'SV', 'alpha_3' => 'SLV', 'numerical' => 222, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'GQ', 'alpha_3' => 'GNQ', 'numerical' => 226, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'ER', 'alpha_3' => 'ERI', 'numerical' => 232, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'EE', 'alpha_3' => 'EST', 'numerical' => 233, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'ET', 'alpha_3' => 'ETH', 'numerical' => 231, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'FK', 'alpha_3' => 'FLK', 'numerical' => 238, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'FO', 'alpha_3' => 'FRO', 'numerical' => 234, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'FJ', 'alpha_3' => 'FJI', 'numerical' => 242, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'FI', 'alpha_3' => 'FIN', 'numerical' => 246, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'FR', 'alpha_3' => 'FRA', 'numerical' => 250, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'GF', 'alpha_3' => 'GUF', 'numerical' => 254, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'PF', 'alpha_3' => 'PYF', 'numerical' => 258, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'TF', 'alpha_3' => 'ATF', 'numerical' => 260, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AN', 'fr' => ''],
			 ['alpha_2' => 'GA', 'alpha_3' => 'GAB', 'numerical' => 266, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'GM', 'alpha_3' => 'GMB', 'numerical' => 270, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'GE', 'alpha_3' => 'GEO', 'numerical' => 268, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'DE', 'alpha_3' => 'DEU', 'numerical' => 276, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'GH', 'alpha_3' => 'GHA', 'numerical' => 288, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'GI', 'alpha_3' => 'GIB', 'numerical' => 292, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'GR', 'alpha_3' => 'GRC', 'numerical' => 300, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'GL', 'alpha_3' => 'GRL', 'numerical' => 304, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'GD', 'alpha_3' => 'GRD', 'numerical' => 308, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'GP', 'alpha_3' => 'GLP', 'numerical' => 312, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'GU', 'alpha_3' => 'GUM', 'numerical' => 316, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'GT', 'alpha_3' => 'GTM', 'numerical' => 320, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'GG', 'alpha_3' => 'GGY', 'numerical' => 831, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'GN', 'alpha_3' => 'GIN', 'numerical' => 324, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'GW', 'alpha_3' => 'GNB', 'numerical' => 624, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'GY', 'alpha_3' => 'GUY', 'numerical' => 328, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'HT', 'alpha_3' => 'HTI', 'numerical' => 332, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'HN', 'alpha_3' => 'HND', 'numerical' => 340, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'HU', 'alpha_3' => 'HUN', 'numerical' => 348, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'IS', 'alpha_3' => 'ISL', 'numerical' => 352, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'IN', 'alpha_3' => 'IND', 'numerical' => 356, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'ID', 'alpha_3' => 'IDN', 'numerical' => 360, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'IR', 'alpha_3' => 'IRN', 'numerical' => 364, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'IQ', 'alpha_3' => 'IRQ', 'numerical' => 368, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'IE', 'alpha_3' => 'IRL', 'numerical' => 372, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'IM', 'alpha_3' => 'IMN', 'numerical' => 833, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'IL', 'alpha_3' => 'ISR', 'numerical' => 376, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'IT', 'alpha_3' => 'ITA', 'numerical' => 380, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'JM', 'alpha_3' => 'JAM', 'numerical' => 388, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'JP', 'alpha_3' => 'JPN', 'numerical' => 392, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'JE', 'alpha_3' => 'JEY', 'numerical' => 832, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'JO', 'alpha_3' => 'JOR', 'numerical' => 400, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'KZ', 'alpha_3' => 'KAZ', 'numerical' => 398, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'KE', 'alpha_3' => 'KEN', 'numerical' => 404, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'KI', 'alpha_3' => 'KIR', 'numerical' => 296, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'KP', 'alpha_3' => 'PRK', 'numerical' => 408, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'KR', 'alpha_3' => 'KOR', 'numerical' => 410, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'KW', 'alpha_3' => 'KWT', 'numerical' => 414, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'KG', 'alpha_3' => 'KGZ', 'numerical' => 417, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'LA', 'alpha_3' => 'LAO', 'numerical' => 418, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'LV', 'alpha_3' => 'LVA', 'numerical' => 428, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'LB', 'alpha_3' => 'LBN', 'numerical' => 422, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'LS', 'alpha_3' => 'LSO', 'numerical' => 426, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'LR', 'alpha_3' => 'LBR', 'numerical' => 430, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'LY', 'alpha_3' => 'LBY', 'numerical' => 434, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'LI', 'alpha_3' => 'LIE', 'numerical' => 438, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'LT', 'alpha_3' => 'LTU', 'numerical' => 440, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'LU', 'alpha_3' => 'LUX', 'numerical' => 442, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'MK', 'alpha_3' => 'MKD', 'numerical' => 807, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'MG', 'alpha_3' => 'MDG', 'numerical' => 450, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'MW', 'alpha_3' => 'MWI', 'numerical' => 454, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'MY', 'alpha_3' => 'MYS', 'numerical' => 458, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'MV', 'alpha_3' => 'MDV', 'numerical' => 462, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'ML', 'alpha_3' => 'MLI', 'numerical' => 466, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'MT', 'alpha_3' => 'MLT', 'numerical' => 470, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'MH', 'alpha_3' => 'MHL', 'numerical' => 584, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'MQ', 'alpha_3' => 'MTQ', 'numerical' => 474, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'MR', 'alpha_3' => 'MRT', 'numerical' => 478, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'MU', 'alpha_3' => 'MUS', 'numerical' => 480, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'YT', 'alpha_3' => 'MYT', 'numerical' => 175, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'MX', 'alpha_3' => 'MEX', 'numerical' => 484, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'FM', 'alpha_3' => 'FSM', 'numerical' => 583, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'MD', 'alpha_3' => 'MDA', 'numerical' => 498, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'MC', 'alpha_3' => 'MCO', 'numerical' => 492, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'MN', 'alpha_3' => 'MNG', 'numerical' => 496, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'ME', 'alpha_3' => 'MNE', 'numerical' => 499, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'MS', 'alpha_3' => 'MSR', 'numerical' => 500, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'MA', 'alpha_3' => 'MAR', 'numerical' => 504, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'MZ', 'alpha_3' => 'MOZ', 'numerical' => 508, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'MM', 'alpha_3' => 'MMR', 'numerical' => 104, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'NA', 'alpha_3' => 'NAM', 'numerical' => 516, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'NR', 'alpha_3' => 'NRU', 'numerical' => 520, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'NP', 'alpha_3' => 'NPL', 'numerical' => 524, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'NL', 'alpha_3' => 'NLD', 'numerical' => 528, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'AN', 'alpha_3' => 'ANT', 'numerical' => 530, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'NC', 'alpha_3' => 'NCL', 'numerical' => 540, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'NZ', 'alpha_3' => 'NZL', 'numerical' => 554, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'NI', 'alpha_3' => 'NIC', 'numerical' => 558, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'NE', 'alpha_3' => 'NER', 'numerical' => 562, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'NG', 'alpha_3' => 'NGA', 'numerical' => 566, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'NU', 'alpha_3' => 'NIU', 'numerical' => 570, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'NF', 'alpha_3' => 'NFK', 'numerical' => 574, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'MP', 'alpha_3' => 'MNP', 'numerical' => 580, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'NO', 'alpha_3' => 'NOR', 'numerical' => 578, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'OM', 'alpha_3' => 'OMN', 'numerical' => 512, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'PK', 'alpha_3' => 'PAK', 'numerical' => 586, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'PW', 'alpha_3' => 'PLW', 'numerical' => 585, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'PS', 'alpha_3' => 'PSE', 'numerical' => 275, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'PA', 'alpha_3' => 'PAN', 'numerical' => 591, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'PG', 'alpha_3' => 'PNG', 'numerical' => 598, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'PY', 'alpha_3' => 'PRY', 'numerical' => 600, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'PE', 'alpha_3' => 'PER', 'numerical' => 604, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'PH', 'alpha_3' => 'PHL', 'numerical' => 608, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'PN', 'alpha_3' => 'PCN', 'numerical' => 612, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'PL', 'alpha_3' => 'POL', 'numerical' => 616, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'PT', 'alpha_3' => 'PRT', 'numerical' => 620, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'PR', 'alpha_3' => 'PRI', 'numerical' => 630, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'QA', 'alpha_3' => 'QAT', 'numerical' => 634, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'RE', 'alpha_3' => 'REU', 'numerical' => 638, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'RO', 'alpha_3' => 'ROU', 'numerical' => 642, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'RU', 'alpha_3' => 'RUS', 'numerical' => 643, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'RW', 'alpha_3' => 'RWA', 'numerical' => 646, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'BL', 'alpha_3' => 'BLM', 'numerical' => 652, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'SH', 'alpha_3' => 'SHN', 'numerical' => 654, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'KN', 'alpha_3' => 'KNA', 'numerical' => 659, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'LC', 'alpha_3' => 'LCA', 'numerical' => 662, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'MF', 'alpha_3' => 'MAF', 'numerical' => 663, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'PM', 'alpha_3' => 'SPM', 'numerical' => 666, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'VC', 'alpha_3' => 'VCT', 'numerical' => 670, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'WS', 'alpha_3' => 'WSM', 'numerical' => 882, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'SM', 'alpha_3' => 'SMR', 'numerical' => 674, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'ST', 'alpha_3' => 'STP', 'numerical' => 678, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'SA', 'alpha_3' => 'SAU', 'numerical' => 682, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'SN', 'alpha_3' => 'SEN', 'numerical' => 686, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'RS', 'alpha_3' => 'SRB', 'numerical' => 688, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'SC', 'alpha_3' => 'SYC', 'numerical' => 690, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'SL', 'alpha_3' => 'SLE', 'numerical' => 694, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'SG', 'alpha_3' => 'SGP', 'numerical' => 702, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'SK', 'alpha_3' => 'SVK', 'numerical' => 703, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'SI', 'alpha_3' => 'SVN', 'numerical' => 705, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'SB', 'alpha_3' => 'SLB', 'numerical' => 90, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'SO', 'alpha_3' => 'SOM', 'numerical' => 706, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'ZA', 'alpha_3' => 'ZAF', 'numerical' => 710, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'ES', 'alpha_3' => 'ESP', 'numerical' => 724, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'LK', 'alpha_3' => 'LKA', 'numerical' => 144, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'SD', 'alpha_3' => 'SDN', 'numerical' => 736, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'SR', 'alpha_3' => 'SUR', 'numerical' => 740, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'SJ', 'alpha_3' => 'SJM', 'numerical' => 744, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'SZ', 'alpha_3' => 'SWZ', 'numerical' => 748, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'SE', 'alpha_3' => 'SWE', 'numerical' => 752, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'CH', 'alpha_3' => 'CHE', 'numerical' => 756, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'SY', 'alpha_3' => 'SYR', 'numerical' => 760, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'TW', 'alpha_3' => 'TWN', 'numerical' => 158, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'TJ', 'alpha_3' => 'TJK', 'numerical' => 762, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'TZ', 'alpha_3' => 'TZA', 'numerical' => 834, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'TH', 'alpha_3' => 'THA', 'numerical' => 764, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'TL', 'alpha_3' => 'TLS', 'numerical' => 626, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'TG', 'alpha_3' => 'TGO', 'numerical' => 768, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'TK', 'alpha_3' => 'TKL', 'numerical' => 772, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'TO', 'alpha_3' => 'TON', 'numerical' => 776, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'TT', 'alpha_3' => 'TTO', 'numerical' => 780, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'TN', 'alpha_3' => 'TUN', 'numerical' => 788, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'TR', 'alpha_3' => 'TUR', 'numerical' => 792, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'TM', 'alpha_3' => 'TKM', 'numerical' => 795, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'TC', 'alpha_3' => 'TCA', 'numerical' => 796, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'TV', 'alpha_3' => 'TUV', 'numerical' => 798, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'UG', 'alpha_3' => 'UGA', 'numerical' => 800, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'UA', 'alpha_3' => 'UKR', 'numerical' => 804, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'AE', 'alpha_3' => 'ARE', 'numerical' => 784, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'GB', 'alpha_3' => 'GBR', 'numerical' => 826, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'EU', 'fr' => ''],
			 ['alpha_2' => 'US', 'alpha_3' => 'USA', 'numerical' => 840, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'UM', 'alpha_3' => 'UMI', 'numerical' => 581, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'UY', 'alpha_3' => 'URY', 'numerical' => 858, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'UZ', 'alpha_3' => 'UZB', 'numerical' => 860, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'VU', 'alpha_3' => 'VUT', 'numerical' => 548, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'VE', 'alpha_3' => 'VEN', 'numerical' => 862, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'SA', 'fr' => ''],
			 ['alpha_2' => 'VN', 'alpha_3' => 'VNM', 'numerical' => 704, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'VI', 'alpha_3' => 'VIR', 'numerical' => 850, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'NA', 'fr' => ''],
			 ['alpha_2' => 'WF', 'alpha_3' => 'WLF', 'numerical' => 876, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'OC', 'fr' => ''],
			 ['alpha_2' => 'EH', 'alpha_3' => 'ESH', 'numerical' => 732, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'YE', 'alpha_3' => 'YEM', 'numerical' => 887, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AS', 'fr' => ''],
			 ['alpha_2' => 'ZM', 'alpha_3' => 'ZMB', 'numerical' => 894, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => ''],
			 ['alpha_2' => 'ZW', 'alpha_3' => 'ZWE', 'numerical' => 716, 'published' => 1, 'citizenship' => 1, 'continent_code' => 'AF', 'fr' => '']
    ];

    public $frOrdering = ['AF', 'ZA', 'AX', 'AL', 'DZ', 'DE', 'AD', 'AO', 'AI', 'AQ', 'AG', 'AN', 'SA', 'AR', 'AM', 'AW', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB',
                          'BY', 'BE', 'BZ', 'BJ', 'BM', 'BT', 'BO', 'BA', 'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CV', 'KY', 'KH', 'CM', 'CA', 'CL', 'CN',
                          'CX', 'CY', 'CC', 'CO', 'KM', 'CG', 'CD', 'CK', 'KR', 'KP', 'CR', 'CI', 'HR', 'CU', 'DK', 'DJ', 'DO', 'DM', 'EG', 'SV', 'AE', 'EC',
                          'ER', 'ES', 'EE', 'US', 'ET', 'FK', 'FO', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'GH', 'GI', 'GR', 'GD', 'GL', 'GP', 'GU', 'GT', 'GG',
                          'GN', 'GW', 'GQ', 'GY', 'GF', 'HT', 'HN', 'HK', 'HU', 'IM', 'UM', 'VG', 'VI', 'IN', 'IO', 'ID', 'IR', 'IQ', 'IE', 'IS', 'IL', 'IT',
                          'JM', 'JP', 'JE', 'JO', 'KZ', 'KE', 'KG', 'KI', 'KW', 'LA', 'LS', 'LV', 'LB', 'LR', 'LY', 'LI', 'LT', 'LU', 'MO', 'MK', 'MG', 'MY', 'MW',
                          'MV', 'ML', 'MT', 'MP', 'MA', 'MH', 'MQ', 'MU', 'MR', 'YT', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MS', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NI',
                          'NE', 'NG', 'NU', 'NF', 'NO', 'NC', 'NZ', 'OM', 'UG', 'UZ', 'PK', 'PW', 'PS', 'PA', 'PG', 'PY', 'NL', 'PE', 'PH', 'PN', 'PL', 'PF', 'PR',
                          'PT', 'QA', 'SY', 'CF', 'RE', 'RO', 'GB', 'RU', 'RW', 'EH', 'BL', 'KN', 'SM', 'MF', 'PM', 'VC', 'SH', 'LC', 'SB', 'WS', 'AS',
                          'ST', 'SN', 'RS', 'SC', 'SL', 'SG', 'SK', 'SI', 'SO', 'SD', 'LK', 'SE', 'CH', 'SR', 'SJ', 'SZ', 'TJ', 'TW', 'TZ', 'TD', 'CZ', 'TF',
                          'TH', 'TL', 'TG', 'TK', 'TO', 'TT', 'TN', 'TM', 'TC', 'TR', 'TV', 'UA', 'UY', 'VU', 'VE', 'VN', 'WF', 'YE', 'ZM', 'ZW'
    ];

    public $languages = [['alpha_2' => 'ab', 'alpha_3' => 'abk'], ['alpha_2' => 'aa', 'alpha_3' => 'aar'],
			 ['alpha_2' => 'af', 'alpha_3' => 'afr'], ['alpha_2' => 'ak', 'alpha_3' => 'aka'],
			 ['alpha_2' => 'sq', 'alpha_3' => 'sqi'], ['alpha_2' => 'am', 'alpha_3' => 'amh'],
			 ['alpha_2' => 'ar', 'alpha_3' => 'ara'], ['alpha_2' => 'an', 'alpha_3' => 'arg'],
			 ['alpha_2' => 'hy', 'alpha_3' => 'hye'], ['alpha_2' => 'as', 'alpha_3' => 'asm'],
			 ['alpha_2' => 'av', 'alpha_3' => 'ava'], ['alpha_2' => 'ae', 'alpha_3' => 'ave'],
			 ['alpha_2' => 'ay', 'alpha_3' => 'aym'], ['alpha_2' => 'az', 'alpha_3' => 'aze'],
			 ['alpha_2' => 'bm', 'alpha_3' => 'bam'], ['alpha_2' => 'ba', 'alpha_3' => 'bak'],
			 ['alpha_2' => 'eu', 'alpha_3' => 'eus'], ['alpha_2' => 'be', 'alpha_3' => 'bel'],
			 ['alpha_2' => 'bn', 'alpha_3' => 'ben'], ['alpha_2' => 'bh', 'alpha_3' => 'bih'],
			 ['alpha_2' => 'bi', 'alpha_3' => 'bis'], ['alpha_2' => 'bs', 'alpha_3' => 'bos'],
			 ['alpha_2' => 'br', 'alpha_3' => 'bre'], ['alpha_2' => 'bg', 'alpha_3' => 'bul'],
			 ['alpha_2' => 'my', 'alpha_3' => 'mya'], ['alpha_2' => 'ca', 'alpha_3' => 'cat'],
			 ['alpha_2' => 'ch', 'alpha_3' => 'cha'], ['alpha_2' => 'ce', 'alpha_3' => 'che'],
			 ['alpha_2' => 'ny', 'alpha_3' => 'nya'], ['alpha_2' => 'zh', 'alpha_3' => 'zho'],
			 ['alpha_2' => 'cv', 'alpha_3' => 'chv'], ['alpha_2' => 'kw', 'alpha_3' => 'cor'],
			 ['alpha_2' => 'co', 'alpha_3' => 'cos'], ['alpha_2' => 'cr', 'alpha_3' => 'cre'],
			 ['alpha_2' => 'hr', 'alpha_3' => 'hrv'], ['alpha_2' => 'cs', 'alpha_3' => 'ces'],
			 ['alpha_2' => 'da', 'alpha_3' => 'dan'], ['alpha_2' => 'dv', 'alpha_3' => 'div'],
			 ['alpha_2' => 'nl', 'alpha_3' => 'nld'], ['alpha_2' => 'dz', 'alpha_3' => 'dzo'],
			 ['alpha_2' => 'en', 'alpha_3' => 'eng'], ['alpha_2' => 'eo', 'alpha_3' => 'epo'],
			 ['alpha_2' => 'et', 'alpha_3' => 'est'], ['alpha_2' => 'ee', 'alpha_3' => 'ewe'],
			 ['alpha_2' => 'fo', 'alpha_3' => 'fao'], ['alpha_2' => 'fj', 'alpha_3' => 'fij'],
			 ['alpha_2' => 'fi', 'alpha_3' => 'fin'], ['alpha_2' => 'fr', 'alpha_3' => 'fra'],
			 ['alpha_2' => 'ff', 'alpha_3' => 'ful'], ['alpha_2' => 'gl', 'alpha_3' => 'glg'],
			 ['alpha_2' => 'lg', 'alpha_3' => 'lug'], ['alpha_2' => 'ka', 'alpha_3' => 'kat'],
			 ['alpha_2' => 'de', 'alpha_3' => 'deu'], ['alpha_2' => 'el', 'alpha_3' => 'ell'],
			 ['alpha_2' => 'kl', 'alpha_3' => 'kal'], ['alpha_2' => 'gn', 'alpha_3' => 'grn'],
			 ['alpha_2' => 'gu', 'alpha_3' => 'guj'], ['alpha_2' => 'ht', 'alpha_3' => 'hat'],
			 ['alpha_2' => 'ha', 'alpha_3' => 'hau'], ['alpha_2' => 'he', 'alpha_3' => 'heb'],
			 ['alpha_2' => 'hz', 'alpha_3' => 'her'], ['alpha_2' => 'hi', 'alpha_3' => 'hin'],
			 ['alpha_2' => 'ho', 'alpha_3' => 'hmo'], ['alpha_2' => 'hu', 'alpha_3' => 'hun'],
			 ['alpha_2' => 'is', 'alpha_3' => 'isl'], ['alpha_2' => 'io', 'alpha_3' => 'ido'],
			 ['alpha_2' => 'ig', 'alpha_3' => 'ibo'], ['alpha_2' => 'id', 'alpha_3' => 'ind'],
			 ['alpha_2' => 'ia', 'alpha_3' => 'ina'], ['alpha_2' => 'ie', 'alpha_3' => 'ile'],
			 ['alpha_2' => 'iu', 'alpha_3' => 'iku'], ['alpha_2' => 'ik', 'alpha_3' => 'ipk'],
			 ['alpha_2' => 'ga', 'alpha_3' => 'gle'], ['alpha_2' => 'it', 'alpha_3' => 'ita'],
			 ['alpha_2' => 'ja', 'alpha_3' => 'jpn'], ['alpha_2' => 'jv', 'alpha_3' => 'jav'],
			 ['alpha_2' => 'kn', 'alpha_3' => 'kan'], ['alpha_2' => 'kr', 'alpha_3' => 'kau'],
			 ['alpha_2' => 'ks', 'alpha_3' => 'kas'], ['alpha_2' => 'kk', 'alpha_3' => 'kaz'],
			 ['alpha_2' => 'km', 'alpha_3' => 'khm'], ['alpha_2' => 'ki', 'alpha_3' => 'kik'],
			 ['alpha_2' => 'rw', 'alpha_3' => 'kin'], ['alpha_2' => 'ky', 'alpha_3' => 'kir'],
			 ['alpha_2' => 'rn', 'alpha_3' => 'run'], ['alpha_2' => 'kv', 'alpha_3' => 'kom'],
			 ['alpha_2' => 'kg', 'alpha_3' => 'kon'], ['alpha_2' => 'ko', 'alpha_3' => 'kor'],
			 ['alpha_2' => 'ku', 'alpha_3' => 'kur'], ['alpha_2' => 'kj', 'alpha_3' => 'kua'],
			 ['alpha_2' => 'lo', 'alpha_3' => 'lao'], ['alpha_2' => 'la', 'alpha_3' => 'lat'],
			 ['alpha_2' => 'lv', 'alpha_3' => 'lav'], ['alpha_2' => 'li', 'alpha_3' => 'lim'],
			 ['alpha_2' => 'ln', 'alpha_3' => 'lin'], ['alpha_2' => 'lt', 'alpha_3' => 'lit'],
			 ['alpha_2' => 'lu', 'alpha_3' => 'lub'], ['alpha_2' => 'lb', 'alpha_3' => 'ltz'],
			 ['alpha_2' => 'mk', 'alpha_3' => 'mkd'], ['alpha_2' => 'mg', 'alpha_3' => 'mlg'],
			 ['alpha_2' => 'ms', 'alpha_3' => 'msa'], ['alpha_2' => 'ml', 'alpha_3' => 'mal'],
			 ['alpha_2' => 'mt', 'alpha_3' => 'mlt'], ['alpha_2' => 'gv', 'alpha_3' => 'glv'],
			 ['alpha_2' => 'mi', 'alpha_3' => 'mri'], ['alpha_2' => 'mr', 'alpha_3' => 'mar'],
			 ['alpha_2' => 'mh', 'alpha_3' => 'mah'], ['alpha_2' => 'mo', 'alpha_3' => 'mol'],
			 ['alpha_2' => 'mn', 'alpha_3' => 'mon'], ['alpha_2' => 'na', 'alpha_3' => 'nau'],
			 ['alpha_2' => 'nv', 'alpha_3' => 'nav'], ['alpha_2' => 'ng', 'alpha_3' => 'ndo'],
			 ['alpha_2' => 'ne', 'alpha_3' => 'nep'], ['alpha_2' => 'nd', 'alpha_3' => 'nde'],
			 ['alpha_2' => 'se', 'alpha_3' => 'sme'], ['alpha_2' => 'no', 'alpha_3' => 'nor'],
			 ['alpha_2' => 'nb', 'alpha_3' => 'nob'], ['alpha_2' => 'nn', 'alpha_3' => 'nno'],
			 ['alpha_2' => 'oc', 'alpha_3' => 'oci'], ['alpha_2' => 'oj', 'alpha_3' => 'oji'],
			 ['alpha_2' => 'cu', 'alpha_3' => 'chu'], ['alpha_2' => 'or', 'alpha_3' => 'ori'],
			 ['alpha_2' => 'om', 'alpha_3' => 'orm'], ['alpha_2' => 'os', 'alpha_3' => 'oss'],
			 ['alpha_2' => 'pi', 'alpha_3' => 'pli'], ['alpha_2' => 'pa', 'alpha_3' => 'pan'],
			 ['alpha_2' => 'ps', 'alpha_3' => 'pus'], ['alpha_2' => 'fa', 'alpha_3' => 'fas'],
			 ['alpha_2' => 'pl', 'alpha_3' => 'pol'], ['alpha_2' => 'pt', 'alpha_3' => 'por'],
			 ['alpha_2' => 'qu', 'alpha_3' => 'que'], ['alpha_2' => 'rc', 'alpha_3' => 'rcf'],
			 ['alpha_2' => 'ro', 'alpha_3' => 'ron'], ['alpha_2' => 'rm', 'alpha_3' => 'roh'],
			 ['alpha_2' => 'ru', 'alpha_3' => 'rus'], ['alpha_2' => 'sm', 'alpha_3' => 'smo'],
			 ['alpha_2' => 'sg', 'alpha_3' => 'sag'], ['alpha_2' => 'sa', 'alpha_3' => 'san'],
			 ['alpha_2' => 'sc', 'alpha_3' => 'srd'], ['alpha_2' => 'gd', 'alpha_3' => 'gla'],
			 ['alpha_2' => 'sr', 'alpha_3' => 'srp'], ['alpha_2' => 'sh', 'alpha_3' => 'hbs'],
			 ['alpha_2' => 'sn', 'alpha_3' => 'sna'], ['alpha_2' => 'ii', 'alpha_3' => 'iii'],
			 ['alpha_2' => 'sd', 'alpha_3' => 'snd'], ['alpha_2' => 'si', 'alpha_3' => 'sin'],
			 ['alpha_2' => 'sk', 'alpha_3' => 'slk'], ['alpha_2' => 'sl', 'alpha_3' => 'slv'],
			 ['alpha_2' => 'so', 'alpha_3' => 'som'], ['alpha_2' => 'st', 'alpha_3' => 'sot'],
			 ['alpha_2' => 'nr', 'alpha_3' => 'nbl'], ['alpha_2' => 'es', 'alpha_3' => 'spa'],
			 ['alpha_2' => 'su', 'alpha_3' => 'sun'], ['alpha_2' => 'sw', 'alpha_3' => 'swa'],
			 ['alpha_2' => 'ss', 'alpha_3' => 'ssw'], ['alpha_2' => 'sv', 'alpha_3' => 'swe'],
			 ['alpha_2' => 'tl', 'alpha_3' => 'tgl'], ['alpha_2' => 'ty', 'alpha_3' => 'tah'],
			 ['alpha_2' => 'tg', 'alpha_3' => 'tgk'], ['alpha_2' => 'ta', 'alpha_3' => 'tam'],
			 ['alpha_2' => 'tt', 'alpha_3' => 'tat'], ['alpha_2' => 'te', 'alpha_3' => 'tel'],
			 ['alpha_2' => 'th', 'alpha_3' => 'tha'], ['alpha_2' => 'bo', 'alpha_3' => 'bod'],
			 ['alpha_2' => 'ti', 'alpha_3' => 'tir'], ['alpha_2' => 'to', 'alpha_3' => 'ton'],
			 ['alpha_2' => 'ts', 'alpha_3' => 'tso'], ['alpha_2' => 'tn', 'alpha_3' => 'tsn'],
			 ['alpha_2' => 'tr', 'alpha_3' => 'tur'], ['alpha_2' => 'tk', 'alpha_3' => 'tuk'],
			 ['alpha_2' => 'tw', 'alpha_3' => 'twi'], ['alpha_2' => 'ug', 'alpha_3' => 'uig'],
			 ['alpha_2' => 'uk', 'alpha_3' => 'ukr'], ['alpha_2' => 'ur', 'alpha_3' => 'urd'],
			 ['alpha_2' => 'uz', 'alpha_3' => 'uzb'], ['alpha_2' => 've', 'alpha_3' => 'ven'],
			 ['alpha_2' => 'vi', 'alpha_3' => 'vie'], ['alpha_2' => 'vo', 'alpha_3' => 'vol'],
			 ['alpha_2' => 'wa', 'alpha_3' => 'wln'], ['alpha_2' => 'cy', 'alpha_3' => 'cym'],
			 ['alpha_2' => 'fy', 'alpha_3' => 'fry'], ['alpha_2' => 'wo', 'alpha_3' => 'wol'],
			 ['alpha_2' => 'xh', 'alpha_3' => 'xho'], ['alpha_2' => 'yi', 'alpha_3' => 'yid'],
			 ['alpha_2' => 'yo', 'alpha_3' => 'yor'], ['alpha_2' => 'za', 'alpha_3' => 'zha'],
			 ['alpha_2' => 'zu', 'alpha_3' => 'zul']
    ];

    public $frLangOrdering = ['ab', 'aa', 'af', 'ak', 'sq', 'de', 'am', 'en', 'ar', 'an', 'hy', 'as', 'av', 
			      'ae', 'ay', 'az', 'ba', 'bm', 'eu', 'bn', 'bi', 'be', 'bh', 'my', 'bs', 'br', 
			      'bg', 'ks', 'ca', 'ch', 'ny', 'zh', 'si', 'ko', 'kw', 'co', 'ht', 'rc', 'cr', 
			      'hr', 'da', 'dz', 'gd', 'es', 'eo', 'et', 'ee', 'fo', 'fj', 'fi', 'fr', 'fy', 
			      'gl', 'cy', 'lg', 'ka', 'el', 'kl', 'gn', 'gu', 'ha', 'he', 'hz', 'hi', 'ho', 
			      'hu', 'io', 'ig', 'id', 'ia', 'iu', 'ik', 'ga', 'is', 'it', 'ja', 'jv', 'kn', 
			      'kr', 'kk', 'km', 'kg', 'ki', 'rw', 'ky', 'rn', 'kv', 'kj', 'ku', 'lo', 'la', 
			      'lv', 'li', 'ln', 'lt', 'lu', 'lb', 'mk', 'ms', 'ml', 'dv', 'mg', 'mt', 'gv', 
			      'mi', 'mr', 'mh', 'mo', 'mn', 'na', 'nv', 'ng', 'nl', 'ne', 'no', 'nb', 'nn', 
			      'nr', 'ie', 'oc', 'oj', 'or', 'om', 'os', 'ug', 'ur', 'uz', 'ps', 'pi', 'pa', 
			      'fa', 'ff', 'pl', 'pt', 'qu', 'rm', 'ro', 'ru', 'se', 'sm', 'sg', 'sa', 'sc', 
			      'sr', 'sh', 'sn', 'nd', 'sd', 'sk', 'sl', 'so', 'st', 'su', 'sv', 'sw', 'ss', 
			      'tg', 'tl', 'ty', 'ta', 'tt', 'cs', 'ce', 'cv', 'te', 'th', 'bo', 'ti', 'to', 
			      'ts', 'tn', 'tr', 'tk', 'tw', 'uk', 've', 'vi', 'cu', 'vo', 'wa', 'wo', 'xh', 
			      'ii', 'yi', 'yo', 'za', 'zu' 
    ];


    public function run()
    {
        foreach ($this->appealCourts as $appealCourt) {
	    DB::table('codalia_profile_appeal_court_list')->insert(['name' => $appealCourt]);
	}

        foreach ($this->countries as $country) {
	    DB::table('codalia_profile_country_list')->insert(['alpha_2' => $country['alpha_2'], 'alpha_3' => $country['alpha_3'],
							       'numerical' => $country['numerical'], 'published' => $country['published'],
							       'citizenship' => $country['citizenship'], 'continent_code' => $country['continent_code'],
							       'fr' => $country['fr']]);
	}

        foreach ($this->frOrdering as $key => $code) {
	    $id = $key + 1;
	    DB::table('codalia_profile_country_list')->where('id', $id)->update(['fr' => $code]);
	}

        foreach ($this->languages as $language) {
	    DB::table('codalia_profile_language_list')->insert(['alpha_2' => $language['alpha_2'], 'alpha_3' => $language['alpha_3'], 'published' => 1]);
	}

        foreach ($this->frLangOrdering as $key => $code) {
	    $id = $key + 1;
	    DB::table('codalia_profile_language_list')->where('id', $id)->update(['fr' => $code]);
	}
    }
}

