<?php namespace Codalia\Profile\Updates;

use Seeder;
use Illuminate\Support\Facades\DB;


class SeedCourtTable extends Seeder
{
    public $courts = ['Section Détachée du Tribunal de Première Instance à Koné',
		      'Section Détachée du Tribunal de Première Instance à Lifou',
		      'Section Détachée du Tribunal de Première Instance à Nuku-Hiva',
		      'Section Détachée du Tribunal de Première Instance à Raïatéa',
		      'Tribunal judiciaire d\'Agen',
		      'Tribunal judiciaire d\'Aix-en-Provence',
		      'Tribunal judiciaire d\'Ajaccio',
		      'Tribunal judiciaire d\'Albertville',
		      'Tribunal judiciaire d\'Albi',
		      'Tribunal judiciaire d\'Alençon',
		      'Tribunal judiciaire d\'Alès',
		      'Tribunal judiciaire d\'Amiens',
		      'Tribunal judiciaire d\'Angers',
		      'Tribunal judiciaire d\'Angoulême',
		      'Tribunal judiciaire d\'Annecy',
		      'Tribunal judiciaire d\'Argentan',
		      'Tribunal judiciaire d\'Arras',
		      'Tribunal judiciaire d\'Auch',
		      'Tribunal judiciaire d\'Aurillac',
		      'Tribunal judiciaire d\'Auxerre',
		      'Tribunal judiciaire d\'Avesnes-sur-Helpe',
		      'Tribunal judiciaire d\'Avignon',
		      'Tribunal judiciaire de Bar-le-Duc',
		      'Tribunal judiciaire de Basse-Terre',
		      'Tribunal judiciaire de Bastia',
		      'Tribunal judiciaire de Bayonne',
		      'Tribunal judiciaire de Beauvais',
		      'Tribunal judiciaire de Belfort',
		      'Tribunal judiciaire de Bergerac',
		      'Tribunal judiciaire de Besançon',
		      'Tribunal judiciaire de Béthune',
		      'Tribunal judiciaire de Béziers',
		      'Tribunal judiciaire de Blois',
		      'Tribunal judiciaire de Bobigny',
		      'Tribunal judiciaire de Bonneville',
		      'Tribunal judiciaire de Bordeaux',
		      'Tribunal judiciaire de Boulogne-sur-Mer',
		      'Tribunal judiciaire de Bourg-en-Bresse',
		      'Tribunal judiciaire de Bourges',
		      'Tribunal judiciaire de Bourgoin-Jallieu',
		      'Tribunal judiciaire de Brest',
		      'Tribunal judiciaire de Brive-la-Gaillarde',
		      'Tribunal judiciaire de Caen',
		      'Tribunal judiciaire de Cahors',
		      'Tribunal judiciaire de Cambrai',
		      'Tribunal judiciaire de Carcassonne',
		      'Tribunal judiciaire de Carpentras',
		      'Tribunal judiciaire de Castres',
		      'Tribunal judiciaire de Cayenne',
		      'Tribunal judiciaire de Châlons-en-Champagne',
		      'Tribunal judiciaire de Chalon-sur-Saône',
		      'Tribunal judiciaire de Chambéry',
		      'Tribunal judiciaire de Charleville-Mézières',
		      'Tribunal judiciaire de Chartres',
		      'Tribunal judiciaire de Châteauroux',
		      'Tribunal judiciaire de Chaumont',
		      'Tribunal judiciaire de Cherbourg-en-Cotentin',
		      'Tribunal judiciaire de Clermont-Ferrand',
		      'Tribunal judiciaire de Colmar',
		      'Tribunal judiciaire de Compiègne',
		      'Tribunal judiciaire de Coutances',
		      'Tribunal judiciaire de Créteil',
		      'Tribunal judiciaire de Cusset',
		      'Tribunal judiciaire de Dax',
		      'Tribunal judiciaire de Dieppe',
		      'Tribunal judiciaire de Digne-les-Bains',
		      'Tribunal judiciaire de Dijon',
		      'Tribunal judiciaire de Douai',
		      'Tribunal judiciaire de Draguignan',
		      'Tribunal judiciaire de Dunkerque',
		      'Tribunal judiciaire d\'Epinal',
		      'Tribunal judiciaire d\'Evreux',
		      'Tribunal judiciaire d\'Évry-Courcouronnes',
		      'Tribunal judiciaire de Foix',
		      'Tribunal judiciaire de Fontainebleau',
		      'Tribunal judiciaire de Fort-de-France',
		      'Tribunal judiciaire de Gap',
		      'Tribunal judiciaire de Grasse',
		      'Tribunal judiciaire de Grenoble',
		      'Tribunal judiciaire de Guéret',
		      'Tribunal judiciaire du Havre',
		      'Tribunal judiciaire de Laon',
		      'Tribunal judiciaire de La Rochelle',
		      'Tribunal judiciaire de La Roche-sur-Yon',
		      'Tribunal judiciaire de Laval',
		      'Tribunal judiciaire de Libourne',
		      'Tribunal judiciaire de Lille',
		      'Tribunal judiciaire de Limoges',
		      'Tribunal judiciaire de Lisieux',
		      'Tribunal judiciaire de Lons-le-Saunier',
		      'Tribunal judiciaire de Lorient',
		      'Tribunal judiciaire de Lyon',
		      'Tribunal judiciaire de Mâcon',
		      'Tribunal judiciaire de Mamoudzou',
		      'Tribunal judiciaire du Mans',
		      'Tribunal judiciaire de Marseille',
		      'Tribunal judiciaire de Meaux',
		      'Tribunal judiciaire de Melun',
		      'Tribunal judiciaire de Mende',
		      'Tribunal judiciaire de Metz',
		      'Tribunal judiciaire de Montargis',
		      'Tribunal judiciaire de Montauban',
		      'Tribunal judiciaire de Montbéliard',
		      'Tribunal judiciaire de Mont-de-Marsan',
		      'Tribunal judiciaire de Montluçon',
		      'Tribunal judiciaire de Montpellier',
		      'Tribunal judiciaire de Moulins',
		      'Tribunal judiciaire de Mulhouse',
		      'Tribunal judiciaire de Nancy',
		      'Tribunal judiciaire de Nanterre',
		      'Tribunal judiciaire de Nantes',
		      'Tribunal judiciaire de Narbonne',
		      'Tribunal judiciaire de Nevers',
		      'Tribunal judiciaire de Nice',
		      'Tribunal judiciaire de Nîmes',
		      'Tribunal judiciaire de Niort',
		      'Tribunal judiciaire d\'Orléans',
		      'Tribunal judiciaire de Paris',
		      'Tribunal judiciaire de Pau',
		      'Tribunal judiciaire de Périgueux',
		      'Tribunal judiciaire de Perpignan',
		      'Tribunal judiciaire de Pointe-à-Pitre',
		      'Tribunal judiciaire de Poitiers',
		      'Tribunal judiciaire de Pontoise',
		      'Tribunal judiciaire de Privas',
		      'Tribunal judiciaire du Puy-en-Velay',
		      'Tribunal judiciaire de Quimper',
		      'Tribunal judiciaire de Reims',
		      'Tribunal judiciaire de Rennes',
		      'Tribunal judiciaire de Roanne',
		      'Tribunal judiciaire de Rodez',
		      'Tribunal judiciaire de Rouen',
		      'Tribunal judiciaire des Sables-d\'Olonne',
		      'Tribunal judiciaire de Saint-Brieuc',
		      'Tribunal judiciaire de Saint-Denis-de-La-Réunion',
		      'Tribunal judiciaire de Saintes',
		      'Tribunal judiciaire de Saint-Etienne',
		      'Tribunal judiciaire de Saint-Malo',
		      'Tribunal judiciaire de Saint-Nazaire',
		      'Tribunal judiciaire de Saint-Omer',
		      'Tribunal judiciaire de Saint-Pierre',
		      'Tribunal judiciaire de Saint-Quentin',
		      'Tribunal judiciaire de Sarreguemines',
		      'Tribunal judiciaire de Saumur',
		      'Tribunal judiciaire de Saverne',
		      'Tribunal judiciaire de Senlis',
		      'Tribunal judiciaire de Sens',
		      'Tribunal judiciaire de Soissons',
		      'Tribunal judiciaire de St Gaudens',
		      'Tribunal judiciaire de Strasbourg',
		      'Tribunal judiciaire de Tarascon',
		      'Tribunal judiciaire de Tarbes',
		      'Tribunal judiciaire de Thionville',
		      'Tribunal judiciaire de Thonon-les-Bains',
		      'Tribunal judiciaire de Toulon',
		      'Tribunal judiciaire de Toulouse',
		      'Tribunal judiciaire de Tours',
		      'Tribunal judiciaire de Troyes',
		      'Tribunal judiciaire de Tulle',
		      'Tribunal judiciaire de Val de Briey',
		      'Tribunal judiciaire de Valence',
		      'Tribunal judiciaire de Valenciennes',
		      'Tribunal judiciaire de Vannes',
		      'Tribunal judiciaire de Verdun',
		      'Tribunal judiciaire de Versailles',
		      'Tribunal judiciaire de Vesoul',
		      'Tribunal judiciaire de Vienne',
		      'Tribunal judiciaire de Villefranche-sur-Saône',
		      'Tribunal de Première Instance de Mata-Utu',
		      'Tribunal de Première Instance de Nouméa',
		      'Tribunal de Première Instance de Papeete',
		      'Tribunal de Première Instance de Saint-Pierre-et-Miquelon',
    ]; 

    public function run()
    {
        foreach ($this->courts as $court) {
	    DB::table('codalia_profile_court_list')->insert(['name' => $court]);
	}
    }
}

